"""
FloodGuard AI — Page 9: Alert History & Notification Status
=============================================================
Displays all alerts generated by the Flood Alert Engine with full
evidence, notification delivery status, human-in-the-loop controls
(acknowledge / resolve), and test alert functionality.

Data transparency:
  - LIVE alerts: generated from real ML predictions + live weather
  - SIMULATION alerts: generated from scenario pipeline runs
  - All alerts are clearly labelled with their origin
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import streamlit as st
import pandas as pd
from datetime import datetime, timezone
from frontend.ui_utils import (
    apply_global_css, header, metric_card, ai_disclaimer,
    demo_badge, simulated_badge, live_badge, section_header, COLORS,
    render_evidence_fusion_bar, _utc_to_ist,
)
from agents.orchestrator import get_orchestrator

st.set_page_config(
    page_title="Alert History — FloodGuard AI",
    page_icon="🚨",
    layout="wide",
    initial_sidebar_state="collapsed",
)
apply_global_css()

# ── CSS ─────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
.alert-card {
    border-radius: 8px;
    padding: 1rem 1.2rem;
    margin-bottom: 0.8rem;
    border-left: 4px solid;
}
.alert-red    { border-color: #ef4444; background: rgba(239,68,68,0.07); }
.alert-orange { border-color: #f97316; background: rgba(249,115,22,0.07); }
.alert-yellow { border-color: #eab308; background: rgba(234,179,8,0.07); }
.alert-green  { border-color: #22c55e; background: rgba(34,197,94,0.07); }
.badge-live { background:#14532d;color:#bbf7d0;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700; }
.badge-sim  { background:#2e1065;color:#c4b5fd;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700; }
.badge-test { background:#3a1a00;color:#fdba74;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700; }
.state-new  { background:#1e3a5f;color:#93c5fd;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600; }
.state-ack  { background:#3a2e00;color:#fde68a;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600; }
.state-res  { background:#14532d;color:#bbf7d0;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600; }
</style>
""", unsafe_allow_html=True)

# ── Init ────────────────────────────────────────────────────────────────────
@st.cache_resource
def get_orch():
    orch = get_orchestrator()
    if not orch.current_state:
        orch.run_pipeline("NORMAL")
    return orch

orch = get_orch()

# Session state
if "notif_status" not in st.session_state:
    st.session_state.notif_status = {}
if "alert_fusion_expanded" not in st.session_state:
    st.session_state.alert_fusion_expanded = set()

# ── Header ──────────────────────────────────────────────────────────────────
header("Alert History", "Flood alerts · Evidence · Notifications · HITL controls", "🚨")

# ── Observability / System Health ───────────────────────────────────────────
st.markdown("---")
with st.expander("🔍 System Health — Live status of all FloodGuard AI components", expanded=False):
    try:
        from services.health_check import get_system_health
        health = get_system_health()
        checks = health.get("checks", [])

        cols = st.columns(min(len(checks), 4))
        for i, c in enumerate(checks):
            col_idx = i % len(cols)
            with cols[col_idx]:
                ok = c.get("ok", False)
                border_color = "#1e3a5f" if ok else "#450a0a"
                st.markdown(
                    f'<div style="background:#1a1d27;border:1px solid {border_color};'
                    f'border-radius:8px;padding:0.6rem 0.8rem;margin-bottom:0.5rem">'
                    f'<div style="font-size:0.72rem;font-weight:700;color:#e2e8f0;margin-bottom:2px">{c["name"]}</div>'
                    f'<div style="font-size:0.8rem;margin-bottom:2px">{c["status"]}</div>'
                    f'<div style="font-size:0.65rem;color:#64748b">{c.get("detail","")[:80]}</div>'
                    f'</div>',
                    unsafe_allow_html=True,
                )

        pct       = health.get("health_pct", 0)
        ok_c      = health.get("ok_count", 0)
        total     = health.get("total_checks", 0)
        checked_at = _utc_to_ist(health.get("checked_at", ""), "%d %b %H:%M IST")
        pct_color = "#22c55e" if pct >= 70 else "#eab308" if pct >= 40 else "#ef4444"
        st.markdown(
            f'<div style="font-size:0.73rem;color:#475569;margin-top:0.3rem">'
            f'System health: <strong style="color:{pct_color}">{pct}%</strong>'
            f' ({ok_c}/{total} components OK) · Checked: {checked_at}'
            f'</div>',
            unsafe_allow_html=True,
        )
    except Exception as exc:
        st.warning(f"Health check unavailable: {exc}")

# ── Notification Channel Status ─────────────────────────────────────────────
st.markdown("---")
section_header("📣 Notification Channels", "Current configuration status")

try:
    from services.notification_service import get_notification_manager
    nm = get_notification_manager()
    ch_status = nm.get_channel_status()

    col_e, col_s, col_w = st.columns(3)
    for col, ch_key, ch_name in [
        (col_e, "email",   "📧 Email"),
        (col_s, "sms",     "📱 SMS"),
        (col_w, "webhook", "🔗 Webhook"),
    ]:
        with col:
            ch = ch_status.get(ch_key, {})
            configured = ch.get("configured", False)
            status_txt = ch.get("status", "&#128308; NOT CONFIGURED")
            note = ch.get("note", "")
            _ch_border = "#1e3a5f" if configured else "#450a0a"
            st.markdown(
                f'<div style="background:#1a1d27;border:1px solid {_ch_border};border-radius:8px;padding:0.8rem 1rem">'
                f'<div style="font-size:0.85rem;font-weight:700;color:#e2e8f0;margin-bottom:0.3rem">{ch_name}</div>'
                f'<div style="font-size:0.78rem;margin-bottom:0.3rem">{status_txt}</div>'
                f'<div style="font-size:0.65rem;color:#475569">{note}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )

    if ch_status.get("test_mode"):
        st.markdown(
            '<div style="background:rgba(249,115,22,0.1);border:1px solid #f97316;border-radius:6px;'
            'padding:0.5rem 0.8rem;font-size:0.75rem;color:#fdba74;margin-top:0.5rem">'
            '&#9888;&#65039; <strong>TEST_NOTIFICATION_MODE is enabled.</strong> '
            'Test alert sends will use real notification channels. Disable after testing.</div>',
            unsafe_allow_html=True,
        )
except Exception as exc:
    st.warning(f"Notification status unavailable: {exc}")

# ── Active Alerts ────────────────────────────────────────────────────────────
st.markdown("---")
section_header("🚨 Active Alerts", "Alerts requiring operator attention")

try:
    from services.flood_alert_engine import get_alert_engine
    engine = get_alert_engine()
    active_alerts = engine.get_active_alerts()
except Exception as exc:
    active_alerts = []
    st.error(f"Alert engine error: {exc}")

# Also read from pipeline state
state = orch.current_state or {}
rich_alerts = state.get("rich_alerts", [])
pipeline_alerts = state.get("alerts", [])

# Merge engine + pipeline alerts (engine takes priority)
all_active = active_alerts or rich_alerts

if not all_active:
    st.markdown("""
<div style="background:#1a1d27;border:1px solid #2d3148;border-radius:8px;
            padding:1.5rem;text-align:center;color:#475569">
    🟢 No active alerts at this time.
</div>
    """, unsafe_allow_html=True)
else:
    for alert in all_active[:10]:
        risk_level = alert.get("risk_level", "GREEN")
        css_class = {
            "RED": "alert-red", "ORANGE": "alert-orange",
            "YELLOW": "alert-yellow", "GREEN": "alert-green",
        }.get(risk_level, "alert-green")

        is_sim  = alert.get("is_simulation", False)
        is_test = alert.get("is_test", False)
        state_v = alert.get("alert_state", "NEW")
        _state_styles = {
            "NEW":          "background:#1e3a5f;color:#93c5fd;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600",
            "ACKNOWLEDGED": "background:#3a2e00;color:#fde68a;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600",
            "RESOLVED":     "background:#14532d;color:#bbf7d0;padding:1px 7px;border-radius:3px;font-size:0.7rem;font-weight:600",
        }
        _s_style = _state_styles.get(state_v, _state_styles["NEW"])
        state_html = f'<span style="{_s_style}">{state_v}</span>'

        badge_html = ""
        if is_test:
            badge_html = '<span style="background:#3a1a00;color:#fdba74;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700">&#x26A0; TEST</span>'
        elif is_sim:
            badge_html = '<span style="background:#2e1065;color:#c4b5fd;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700">&#x1F7E3; SIMULATION</span>'
        else:
            badge_html = '<span style="background:#14532d;color:#bbf7d0;padding:2px 7px;border-radius:4px;font-size:0.65rem;font-weight:700">&#x1F7E2; LIVE</span>'

        evidence_html = "".join(
            f"<li style='color:#94a3b8;font-size:0.73rem'>{e}</li>"
            for e in alert.get("evidence", [])[:5]
        )

        conf_pct    = round(alert.get("confidence", 0) * 100)
        window      = alert.get("expected_window", "Unknown")
        score       = alert.get("risk_score", 0)
        location    = alert.get("location", "Unknown")
        ts          = _utc_to_ist(alert.get("timestamp", ""), "%d %b %H:%M IST")
        event_id    = alert.get("event_id", "")
        rec_action  = alert.get("recommended_action", "Review dashboard.")
        trigger_txt = alert.get("trigger", "")
        data_status = alert.get("data_status", "")
        data_status_map: dict = alert.get("data_status_map", {})

        _alert_card_styles = {
            "alert-red":    "border-left:4px solid #ef4444;background:rgba(239,68,68,0.07)",
            "alert-orange": "border-left:4px solid #f97316;background:rgba(249,115,22,0.07)",
            "alert-yellow": "border-left:4px solid #eab308;background:rgba(234,179,8,0.07)",
            "alert-green":  "border-left:4px solid #22c55e;background:rgba(34,197,94,0.07)",
        }
        _card_style = _alert_card_styles.get(css_class, _alert_card_styles["alert-green"])
        _trigger_row = (
            f'<div style="margin:0.4rem 0;padding:0.35rem 0.6rem;background:rgba(249,115,22,0.08);'
            f'border-radius:4px;border-left:3px solid #f97316">'
            f'<span style="font-size:0.62rem;color:#f97316;font-weight:700">TRIGGER: </span>'
            f'<span style="font-size:0.72rem;color:#fde68a">{trigger_txt}</span></div>'
        ) if trigger_txt else ""
        _dstatus_row = (
            f'<div style="margin:0.3rem 0;font-size:0.65rem;color:#64748b">'
            f'<span style="font-weight:600">DATA STATUS: </span>{data_status}</div>'
        ) if data_status else ""
        _score_str = f"{score:.0f}/100"
        st.markdown(
            f'<div style="border-radius:8px;padding:1rem 1.2rem;margin-bottom:0.8rem;{_card_style}">'
            f'<div style="display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:0.5rem">'
            f'<div>'
            f'<div style="font-size:1rem;font-weight:800;color:#e2e8f0;margin-bottom:0.3rem">&#128680; {risk_level} FLOOD ALERT &mdash; {location}</div>'
            f'<div style="display:flex;gap:0.4rem;flex-wrap:wrap;margin-bottom:0.5rem">'
            f'{badge_html} {state_html}'
            f'<span style="font-size:0.65rem;color:#64748b">ID: {event_id}</span>'
            f'</div></div>'
            f'<div style="text-align:right;font-size:0.7rem;color:#64748b">{ts}</div>'
            f'</div>'
            f'<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:0.8rem;margin:0.5rem 0">'
            f'<div><div style="font-size:0.65rem;color:#64748b;text-transform:uppercase;font-weight:600">Risk Score</div>'
            f'<div style="font-size:1.1rem;font-weight:700;color:#e2e8f0">{_score_str}</div></div>'
            f'<div><div style="font-size:0.65rem;color:#64748b;text-transform:uppercase;font-weight:600">Confidence</div>'
            f'<div style="font-size:1.1rem;font-weight:700;color:#e2e8f0">{conf_pct}%</div></div>'
            f'<div><div style="font-size:0.65rem;color:#64748b;text-transform:uppercase;font-weight:600">Expected Risk Window</div>'
            f'<div style="font-size:0.8rem;font-weight:600;color:#fde68a">{window}</div></div>'
            f'</div>'
            f'<div style="margin:0.5rem 0">'
            f'<div style="font-size:0.65rem;color:#64748b;font-weight:600;margin-bottom:0.3rem">EVIDENCE</div>'
            f'<ul style="margin:0;padding-left:1.2rem">{evidence_html}</ul>'
            f'</div>'
            f'{_trigger_row}{_dstatus_row}'
            f'<div style="margin-top:0.5rem;padding:0.4rem 0.6rem;background:rgba(0,0,0,0.2);border-radius:4px">'
            f'<span style="font-size:0.65rem;color:#64748b;font-weight:600">RECOMMENDED ACTION:</span>'
            f'<span style="font-size:0.73rem;color:#cbd5e1;margin-left:0.3rem">{rec_action[:200]}</span>'
            f'</div></div>',
            unsafe_allow_html=True,
        )

        # Data Status per-factor breakdown
        if data_status_map:
            _dsm_badges = "".join(
                f'<span style="background:#1e2440;color:#94a3b8;border-radius:3px;padding:1px 5px;font-size:0.62rem;margin-right:4px">'
                f'<strong style="color:#cbd5e1">{k.replace("_"," ").title()}:</strong> {v}</span>'
                for k, v in data_status_map.items()
            )
            st.markdown(
                f'<div style="margin:-0.4rem 0 0.6rem 0;font-size:0.62rem;color:#64748b">'
                f'<span style="font-weight:600;margin-right:6px">DATA LABELS:</span>{_dsm_badges}</div>',
                unsafe_allow_html=True,
            )

        # ── Evidence Fusion Breakdown (Sub-Task A) ────────────────────────────
        _ev_scores = alert.get("evidence_scores", {})
        _fw_scores  = alert.get("fusion_weights", {})
        if _ev_scores:
            with st.expander(f"📊 Evidence Fusion Detail — {location}", expanded=False):
                render_evidence_fusion_bar(_ev_scores, _fw_scores)

        # HITL controls for ORANGE/RED
        if risk_level in ("RED", "ORANGE") and state_v == "NEW":
            col_ack, col_res, col_notif = st.columns([1, 1, 2])

            with col_ack:
                if st.button(f"✅ Acknowledge", key=f"ack_{event_id}"):
                    try:
                        engine.acknowledge_alert(event_id, operator="operator")
                        st.success("Alert acknowledged")
                        st.rerun()
                    except Exception as e:
                        st.error(str(e))

            with col_res:
                if st.button(f"🔒 Resolve", key=f"res_{event_id}"):
                    try:
                        engine.resolve_alert(event_id, outcome="Resolved by operator")
                        st.success("Alert resolved")
                        st.rerun()
                    except Exception as e:
                        st.error(str(e))

            with col_notif:
                if st.button(f"📣 Dispatch Notification", key=f"notif_{event_id}",
                             help="Send alert via configured channels (Email/SMS/Webhook)"):
                    if is_sim or is_test:
                        st.warning("⚠️ Simulation/test alerts require TEST_NOTIFICATION_MODE=true to send real notifications.")
                    else:
                        try:
                            from services.notification_service import get_notification_manager
                            nm2 = get_notification_manager()
                            result = nm2.dispatch(alert)
                            st.session_state.notif_status[event_id] = result
                            if result["status"] == "SENT":
                                st.success(f"Notification sent via {result['sent_count']} channel(s)")
                            elif result["status"] == "SKIPPED":
                                st.warning(f"Notification channels not configured. {result.get('reason','')}")
                            else:
                                st.error(f"Notification failed: {result}")
                        except Exception as e:
                            st.error(f"Notification error: {e}")

        # Show previous notification status if available
        if event_id in st.session_state.notif_status:
            ns = st.session_state.notif_status[event_id]
            _ns_status = ns.get('status', '?')
            _ns_at = ns.get('dispatched_at', '')[:19]
            st.markdown(
                f'<div style="font-size:0.7rem;color:#64748b;margin-bottom:0.5rem">'
                f'Last notification: {_ns_status} at {_ns_at} &mdash; '
                f'Sent: {ns.get("sent_count",0)} | Skipped: {ns.get("skipped_count",0)} | Failed: {ns.get("failed_count",0)}'
                f'</div>',
                unsafe_allow_html=True,
            )

# ── Test Alert Section ───────────────────────────────────────────────────────
st.markdown("---")
section_header("🧪 Test Alert", "Generate a test notification — for demonstration only")

st.markdown("""
<div style="background:rgba(249,115,22,0.08);border:1px solid #f97316;border-radius:8px;
            padding:0.8rem 1rem;margin-bottom:1rem;font-size:0.8rem;color:#fdba74">
    ⚠️ <strong>Test alerts</strong> are clearly labelled "TEST ALERT — NOT A REAL EMERGENCY".<br>
    Real notification sends (Email/SMS/Webhook) require <code>TEST_NOTIFICATION_MODE=true</code> in environment.<br>
    Never use test mode in a production/operational deployment.
</div>
""", unsafe_allow_html=True)

test_location = st.text_input(
    "Test location name",
    value="Limbayat, Surat",
    key="test_location",
    help="Location label for the test alert",
)

col_gen, col_send = st.columns([1, 1])
with col_gen:
    if st.button("⚡ Generate Test Alert (display only)", use_container_width=True):
        try:
            engine2 = get_alert_engine()
            test_alert = engine2.generate_test_alert(test_location)
            st.session_state["last_test_alert"] = test_alert
            st.success(f"Test alert generated: {test_alert['event_id']}")
        except Exception as e:
            st.error(str(e))

with col_send:
    if st.button("📣 Send Test Notification", use_container_width=True,
                 help="Requires TEST_NOTIFICATION_MODE=true"):
        try:
            from services.notification_service import get_notification_manager
            nm3 = get_notification_manager()
            engine3 = get_alert_engine()
            test_alert3 = engine3.generate_test_alert(test_location)
            result3 = nm3.dispatch(test_alert3, is_test=True)
            if result3["status"] == "BLOCKED":
                st.warning(f"⚠️ {result3.get('reason', 'Test notifications blocked.')}")
            elif result3["status"] == "SENT":
                st.success(f"Test notification sent via {result3['sent_count']} channel(s)")
            else:
                st.warning(f"Test notification skipped: {result3}")
        except Exception as e:
            st.error(f"Test notification error: {e}")

if "last_test_alert" in st.session_state:
    ta = st.session_state["last_test_alert"]
    _ta_risk = f"{ta.get('risk_level','')} ({ta.get('risk_score',0):.0f}/100)"
    _ta_conf = f"{round(ta.get('confidence',0)*100)}%"
    st.markdown(
        f'<div style="background:#1a1d27;border:1px solid #f97316;border-radius:8px;padding:1rem;margin-top:0.5rem">'
        f'<div style="font-size:0.7rem;color:#fdba74;font-weight:700;margin-bottom:0.4rem">&#9888;&#65039; TEST ALERT &mdash; NOT A REAL EMERGENCY</div>'
        f'<div style="font-size:0.85rem;color:#e2e8f0">'
        f'<strong>ID:</strong> {ta.get("event_id","")}<br>'
        f'<strong>Location:</strong> {ta.get("location","")}<br>'
        f'<strong>Risk:</strong> {_ta_risk}<br>'
        f'<strong>Window:</strong> {ta.get("expected_window","")}<br>'
        f'<strong>Confidence:</strong> {_ta_conf}<br>'
        f'</div></div>',
        unsafe_allow_html=True,
    )

# ── Historical Alerts from DB ────────────────────────────────────────────────
st.markdown("---")
section_header("📋 Alert Database", "All alerts stored in SQLite")

try:
    from services.database import get_alerts as db_get_alerts
    db_alerts = db_get_alerts(limit=50)
    if db_alerts:
        df_alerts = pd.DataFrame(db_alerts)
        display_cols = ["event_id", "location", "risk_level", "risk_score",
                        "alert_state", "created_at", "acknowledged_at", "resolved_at"]
        display_cols = [c for c in display_cols if c in df_alerts.columns]
        if display_cols:
            st.dataframe(
                df_alerts[display_cols].rename(columns={
                    "event_id": "ID", "location": "Location",
                    "risk_level": "Level", "risk_score": "Score",
                    "alert_state": "State", "created_at": "Created",
                    "acknowledged_at": "Ack'd", "resolved_at": "Resolved",
                }),
                use_container_width=True,
                hide_index=True,
            )
    else:
        st.info("No alerts in database yet. Run a pipeline scenario to generate alerts.")
except Exception as exc:
    st.warning(f"Could not load alert database: {exc}")

# ── Footer ───────────────────────────────────────────────────────────────────
st.markdown("---")
ai_disclaimer()
st.markdown("""
<div style="text-align:center;font-size:0.7rem;color:#475569;padding-top:0.5rem">
    <strong>DATA TRANSPARENCY</strong> — All flood alerts are AI-generated decision-support outputs.
    They require authorized human operator review and verification before any emergency response action.
    This system does not constitute an official government emergency notification service.
    Alert notifications (Email/SMS/Webhook) are only sent if explicitly configured and enabled.
</div>
""", unsafe_allow_html=True)
